### ISSUE TITLE
Clarification on locking while data migration

### ISSUE THREAD

**Issue by mdubey-babylon** [Cobliteam/cassandra-migrate#41]
Hi

This is not an issue as such, we just wanted how this works. We are evaluating different NoSQL databases for our project and Cassandra is One of them. We wanted to evaluate Live Migration when we came across this tool. We have got a specific question about the locking.

1.  I was not sure if locking was possible in cassandra, but your readme says that `Supports locking for concurrent instances using Lightweight Transactions`. What does that mean? Do you lock the keyspace or lock just the table while running the migration.

2. Suppose we do a `add index(secondary)`/`add column` while a lot of data is already inserted which might take some time to create indexes for all the existing data. What sort of downtime we are going to face. 
      - Is it that the keyspace will not be accessible for the whole time? 
      - Or the table will not be accessible for the whole time? 
      - Or everything else can work but we cannot use that secondary index till all the data is indexed, which sounds obvious?

Please let us know.
Thank You

**Comment by danielkza** [comment]
The locking mechanism only prevents cassandra-migrate instances from racing
with *each other*.  It does not help with consistency from the point of
view of the clients accessing the data on the tables that are being
migrated.

The way it works is actually pretty simple: before applying any migrations,
we write an "in progress" entry in the migration state table with a random
ID, but only if no other "in progress" entries exist. We then read the "in
progress" entries again; if we get the same ID we generated we can proceed,
otherwise another instance of the program was faster, and we need to start
over.

The main purpose of that scheme is to support the pattern of migrating
tables at application start when you are running multiple application
instances.

Cassandra does not provide data model transactions or strong consistency in
general, and this tool can't really change that. AFAIK keyspaces can never
be "locked", and altering one table does not affect service for other
tables in the same keyspace. I believe that secondary index rebuilds do not
lock their parent tables at all. The docs are not clear on whether they are
accessible with partial data or not, but I have not investigated in depth.

Em sex, 12 de out de 2018 03:01, mdubey-babylon <notifications@github.com>
escreveu:

**Comment by mdubey-babylon** [comment]
@danielkza, thanks for your response. I will close this issue as of now. The main question I had on what sort of locking we are talking in the README.
